// 中国省市区基础数据（API不可用时的回退方案）
// 数据来源：民政部行政区划代码（精简版，仅含省/市/区三级）

export interface RegionItem {
    adcode: string;
    name: string;
    level: 'province' | 'city' | 'district';
}

// 省级数据（34个省级行政区）
export const PROVINCES: RegionItem[] = [
    { adcode: '110000', name: '北京市', level: 'province' },
    { adcode: '120000', name: '天津市', level: 'province' },
    { adcode: '130000', name: '河北省', level: 'province' },
    { adcode: '140000', name: '山西省', level: 'province' },
    { adcode: '150000', name: '内蒙古自治区', level: 'province' },
    { adcode: '210000', name: '辽宁省', level: 'province' },
    { adcode: '220000', name: '吉林省', level: 'province' },
    { adcode: '230000', name: '黑龙江省', level: 'province' },
    { adcode: '310000', name: '上海市', level: 'province' },
    { adcode: '320000', name: '江苏省', level: 'province' },
    { adcode: '330000', name: '浙江省', level: 'province' },
    { adcode: '340000', name: '安徽省', level: 'province' },
    { adcode: '350000', name: '福建省', level: 'province' },
    { adcode: '360000', name: '江西省', level: 'province' },
    { adcode: '370000', name: '山东省', level: 'province' },
    { adcode: '410000', name: '河南省', level: 'province' },
    { adcode: '420000', name: '湖北省', level: 'province' },
    { adcode: '430000', name: '湖南省', level: 'province' },
    { adcode: '440000', name: '广东省', level: 'province' },
    { adcode: '450000', name: '广西壮族自治区', level: 'province' },
    { adcode: '460000', name: '海南省', level: 'province' },
    { adcode: '500000', name: '重庆市', level: 'province' },
    { adcode: '510000', name: '四川省', level: 'province' },
    { adcode: '520000', name: '贵州省', level: 'province' },
    { adcode: '530000', name: '云南省', level: 'province' },
    { adcode: '540000', name: '西藏自治区', level: 'province' },
    { adcode: '610000', name: '陕西省', level: 'province' },
    { adcode: '620000', name: '甘肃省', level: 'province' },
    { adcode: '630000', name: '青海省', level: 'province' },
    { adcode: '640000', name: '宁夏回族自治区', level: 'province' },
    { adcode: '650000', name: '新疆维吾尔自治区', level: 'province' },
    { adcode: '710000', name: '台湾省', level: 'province' },
    { adcode: '810000', name: '香港特别行政区', level: 'province' },
    { adcode: '820000', name: '澳门特别行政区', level: 'province' },
];

// 市级数据（按省级 adcode 分组）
export const CITIES: Record<string, RegionItem[]> = {
    '110000': [{ adcode: '110100', name: '北京市', level: 'city' }],
    '120000': [{ adcode: '120100', name: '天津市', level: 'city' }],
    '130000': [
        { adcode: '130100', name: '石家庄市', level: 'city' },
        { adcode: '130200', name: '唐山市', level: 'city' },
        { adcode: '130300', name: '秦皇岛市', level: 'city' },
        { adcode: '130400', name: '邯郸市', level: 'city' },
        { adcode: '130500', name: '邢台市', level: 'city' },
        { adcode: '130600', name: '保定市', level: 'city' },
        { adcode: '130700', name: '张家口市', level: 'city' },
        { adcode: '130800', name: '承德市', level: 'city' },
        { adcode: '130900', name: '沧州市', level: 'city' },
        { adcode: '131000', name: '廊坊市', level: 'city' },
        { adcode: '131100', name: '衡水市', level: 'city' },
    ],
    '220000': [
        { adcode: '220100', name: '长春市', level: 'city' },
        { adcode: '220200', name: '吉林市', level: 'city' },
        { adcode: '220300', name: '四平市', level: 'city' },
        { adcode: '220400', name: '辽源市', level: 'city' },
        { adcode: '220500', name: '通化市', level: 'city' },
        { adcode: '220600', name: '白山市', level: 'city' },
        { adcode: '220700', name: '松原市', level: 'city' },
        { adcode: '220800', name: '白城市', level: 'city' },
        { adcode: '222400', name: '延边朝鲜族自治州', level: 'city' },
    ],
    '310000': [{ adcode: '310100', name: '上海市', level: 'city' }],
    '320000': [
        { adcode: '320100', name: '南京市', level: 'city' },
        { adcode: '320200', name: '无锡市', level: 'city' },
        { adcode: '320300', name: '徐州市', level: 'city' },
        { adcode: '320400', name: '常州市', level: 'city' },
        { adcode: '320500', name: '苏州市', level: 'city' },
        { adcode: '320600', name: '南通市', level: 'city' },
        { adcode: '320700', name: '连云港市', level: 'city' },
        { adcode: '320800', name: '淮安市', level: 'city' },
        { adcode: '320900', name: '盐城市', level: 'city' },
        { adcode: '321000', name: '扬州市', level: 'city' },
        { adcode: '321100', name: '镇江市', level: 'city' },
        { adcode: '321200', name: '泰州市', level: 'city' },
        { adcode: '321300', name: '宿迁市', level: 'city' },
    ],
    '330000': [
        { adcode: '330100', name: '杭州市', level: 'city' },
        { adcode: '330200', name: '宁波市', level: 'city' },
        { adcode: '330300', name: '温州市', level: 'city' },
        { adcode: '330400', name: '嘉兴市', level: 'city' },
        { adcode: '330500', name: '湖州市', level: 'city' },
        { adcode: '330600', name: '绍兴市', level: 'city' },
        { adcode: '330700', name: '金华市', level: 'city' },
        { adcode: '330800', name: '衢州市', level: 'city' },
        { adcode: '330900', name: '舟山市', level: 'city' },
        { adcode: '331000', name: '台州市', level: 'city' },
        { adcode: '331100', name: '丽水市', level: 'city' },
    ],
    '440000': [
        { adcode: '440100', name: '广州市', level: 'city' },
        { adcode: '440200', name: '韶关市', level: 'city' },
        { adcode: '440300', name: '深圳市', level: 'city' },
        { adcode: '440400', name: '珠海市', level: 'city' },
        { adcode: '440500', name: '汕头市', level: 'city' },
        { adcode: '440600', name: '佛山市', level: 'city' },
        { adcode: '440700', name: '江门市', level: 'city' },
        { adcode: '440800', name: '湛江市', level: 'city' },
        { adcode: '440900', name: '茂名市', level: 'city' },
        { adcode: '441200', name: '肇庆市', level: 'city' },
        { adcode: '441300', name: '惠州市', level: 'city' },
        { adcode: '441400', name: '梅州市', level: 'city' },
        { adcode: '441500', name: '汕尾市', level: 'city' },
        { adcode: '441600', name: '河源市', level: 'city' },
        { adcode: '441700', name: '阳江市', level: 'city' },
        { adcode: '441800', name: '清远市', level: 'city' },
        { adcode: '441900', name: '东莞市', level: 'city' },
        { adcode: '442000', name: '中山市', level: 'city' },
        { adcode: '445100', name: '潮州市', level: 'city' },
        { adcode: '445200', name: '揭阳市', level: 'city' },
        { adcode: '445300', name: '云浮市', level: 'city' },
    ],
    '510000': [
        { adcode: '510100', name: '成都市', level: 'city' },
        { adcode: '510300', name: '自贡市', level: 'city' },
        { adcode: '510400', name: '攀枝花市', level: 'city' },
        { adcode: '510500', name: '泸州市', level: 'city' },
        { adcode: '510600', name: '德阳市', level: 'city' },
        { adcode: '510700', name: '绵阳市', level: 'city' },
        { adcode: '510800', name: '广元市', level: 'city' },
        { adcode: '510900', name: '遂宁市', level: 'city' },
        { adcode: '511000', name: '内江市', level: 'city' },
        { adcode: '511100', name: '乐山市', level: 'city' },
        { adcode: '511300', name: '南充市', level: 'city' },
        { adcode: '511400', name: '眉山市', level: 'city' },
        { adcode: '511500', name: '宜宾市', level: 'city' },
        { adcode: '511600', name: '广安市', level: 'city' },
        { adcode: '511700', name: '达州市', level: 'city' },
        { adcode: '511800', name: '雅安市', level: 'city' },
        { adcode: '511900', name: '巴中市', level: 'city' },
        { adcode: '512000', name: '资阳市', level: 'city' },
    ],
    '500000': [{ adcode: '500100', name: '重庆市', level: 'city' }],
};

// 区级数据（按市级 adcode 分组，仅含主要城市的区）
export const DISTRICTS: Record<string, RegionItem[]> = {
    '110100': [
        { adcode: '110101', name: '东城区', level: 'district' },
        { adcode: '110102', name: '西城区', level: 'district' },
        { adcode: '110105', name: '朝阳区', level: 'district' },
        { adcode: '110106', name: '丰台区', level: 'district' },
        { adcode: '110107', name: '石景山区', level: 'district' },
        { adcode: '110108', name: '海淀区', level: 'district' },
        { adcode: '110109', name: '门头沟区', level: 'district' },
        { adcode: '110111', name: '房山区', level: 'district' },
        { adcode: '110112', name: '通州区', level: 'district' },
        { adcode: '110113', name: '顺义区', level: 'district' },
        { adcode: '110114', name: '昌平区', level: 'district' },
        { adcode: '110115', name: '大兴区', level: 'district' },
        { adcode: '110116', name: '怀柔区', level: 'district' },
        { adcode: '110117', name: '平谷区', level: 'district' },
        { adcode: '110118', name: '密云区', level: 'district' },
        { adcode: '110119', name: '延庆区', level: 'district' },
    ],
    '220100': [
        { adcode: '220102', name: '南关区', level: 'district' },
        { adcode: '220103', name: '宽城区', level: 'district' },
        { adcode: '220104', name: '朝阳区', level: 'district' },
        { adcode: '220105', name: '二道区', level: 'district' },
        { adcode: '220106', name: '绿园区', level: 'district' },
        { adcode: '220112', name: '双阳区', level: 'district' },
        { adcode: '220113', name: '九台区', level: 'district' },
        { adcode: '220122', name: '农安县', level: 'district' },
        { adcode: '220171', name: '长春经济技术开发区', level: 'district' },
        { adcode: '220172', name: '长春净月高新技术产业开发区', level: 'district' },
        { adcode: '220182', name: '榆树市', level: 'district' },
        { adcode: '220183', name: '德惠市', level: 'district' },
    ],
    '220200': [
        { adcode: '220202', name: '昌邑区', level: 'district' },
        { adcode: '220203', name: '龙潭区', level: 'district' },
        { adcode: '220204', name: '船营区', level: 'district' },
        { adcode: '220211', name: '丰满区', level: 'district' },
        { adcode: '220221', name: '永吉县', level: 'district' },
        { adcode: '220281', name: '蛟河市', level: 'district' },
        { adcode: '220282', name: '桦甸市', level: 'district' },
        { adcode: '220283', name: '舒兰市', level: 'district' },
        { adcode: '220284', name: '磐石市', level: 'district' },
    ],
    '310100': [
        { adcode: '310101', name: '黄浦区', level: 'district' },
        { adcode: '310104', name: '徐汇区', level: 'district' },
        { adcode: '310105', name: '长宁区', level: 'district' },
        { adcode: '310106', name: '静安区', level: 'district' },
        { adcode: '310107', name: '普陀区', level: 'district' },
        { adcode: '310109', name: '虹口区', level: 'district' },
        { adcode: '310110', name: '杨浦区', level: 'district' },
        { adcode: '310112', name: '闵行区', level: 'district' },
        { adcode: '310113', name: '宝山区', level: 'district' },
        { adcode: '310114', name: '嘉定区', level: 'district' },
        { adcode: '310115', name: '浦东新区', level: 'district' },
        { adcode: '310116', name: '金山区', level: 'district' },
        { adcode: '310117', name: '松江区', level: 'district' },
        { adcode: '310118', name: '青浦区', level: 'district' },
        { adcode: '310120', name: '奉贤区', level: 'district' },
        { adcode: '310151', name: '崇明区', level: 'district' },
    ],
    '320100': [
        { adcode: '320102', name: '玄武区', level: 'district' },
        { adcode: '320104', name: '秦淮区', level: 'district' },
        { adcode: '320105', name: '建邺区', level: 'district' },
        { adcode: '320106', name: '鼓楼区', level: 'district' },
        { adcode: '320111', name: '浦口区', level: 'district' },
        { adcode: '320113', name: '栖霞区', level: 'district' },
        { adcode: '320114', name: '雨花台区', level: 'district' },
        { adcode: '320115', name: '江宁区', level: 'district' },
        { adcode: '320116', name: '六合区', level: 'district' },
        { adcode: '320117', name: '溧水区', level: 'district' },
        { adcode: '320118', name: '高淳区', level: 'district' },
    ],
    '330100': [
        { adcode: '330102', name: '上城区', level: 'district' },
        { adcode: '330105', name: '拱墅区', level: 'district' },
        { adcode: '330106', name: '西湖区', level: 'district' },
        { adcode: '330108', name: '滨江区', level: 'district' },
        { adcode: '330109', name: '萧山区', level: 'district' },
        { adcode: '330110', name: '余杭区', level: 'district' },
        { adcode: '330111', name: '富阳区', level: 'district' },
        { adcode: '330112', name: '临安区', level: 'district' },
        { adcode: '330113', name: '临平区', level: 'district' },
        { adcode: '330114', name: '钱塘区', level: 'district' },
        { adcode: '330122', name: '桐庐县', level: 'district' },
        { adcode: '330127', name: '淳安县', level: 'district' },
        { adcode: '330182', name: '建德市', level: 'district' },
    ],
    '440100': [
        { adcode: '440103', name: '荔湾区', level: 'district' },
        { adcode: '440104', name: '越秀区', level: 'district' },
        { adcode: '440105', name: '海珠区', level: 'district' },
        { adcode: '440106', name: '天河区', level: 'district' },
        { adcode: '440111', name: '白云区', level: 'district' },
        { adcode: '440112', name: '黄埔区', level: 'district' },
        { adcode: '440113', name: '番禺区', level: 'district' },
        { adcode: '440114', name: '花都区', level: 'district' },
        { adcode: '440115', name: '南沙区', level: 'district' },
        { adcode: '440117', name: '从化区', level: 'district' },
        { adcode: '440118', name: '增城区', level: 'district' },
    ],
    '440300': [
        { adcode: '440303', name: '罗湖区', level: 'district' },
        { adcode: '440304', name: '福田区', level: 'district' },
        { adcode: '440305', name: '南山区', level: 'district' },
        { adcode: '440306', name: '宝安区', level: 'district' },
        { adcode: '440307', name: '龙岗区', level: 'district' },
        { adcode: '440308', name: '盐田区', level: 'district' },
        { adcode: '440309', name: '龙华区', level: 'district' },
        { adcode: '440310', name: '坪山区', level: 'district' },
        { adcode: '440311', name: '光明区', level: 'district' },
    ],
    '510100': [
        { adcode: '510104', name: '锦江区', level: 'district' },
        { adcode: '510105', name: '青羊区', level: 'district' },
        { adcode: '510106', name: '金牛区', level: 'district' },
        { adcode: '510107', name: '武侯区', level: 'district' },
        { adcode: '510108', name: '成华区', level: 'district' },
        { adcode: '510112', name: '龙泉驿区', level: 'district' },
        { adcode: '510113', name: '青白江区', level: 'district' },
        { adcode: '510114', name: '新都区', level: 'district' },
        { adcode: '510115', name: '温江区', level: 'district' },
        { adcode: '510116', name: '双流区', level: 'district' },
        { adcode: '510117', name: '郫都区', level: 'district' },
        { adcode: '510118', name: '新津区', level: 'district' },
        { adcode: '510121', name: '金堂县', level: 'district' },
        { adcode: '510129', name: '大邑县', level: 'district' },
        { adcode: '510131', name: '蒲江县', level: 'district' },
        { adcode: '510181', name: '都江堰市', level: 'district' },
        { adcode: '510182', name: '彭州市', level: 'district' },
        { adcode: '510183', name: '邛崃市', level: 'district' },
        { adcode: '510184', name: '崇州市', level: 'district' },
        { adcode: '510185', name: '简阳市', level: 'district' },
    ],
    '500100': [
        { adcode: '500101', name: '万州区', level: 'district' },
        { adcode: '500102', name: '涪陵区', level: 'district' },
        { adcode: '500103', name: '渝中区', level: 'district' },
        { adcode: '500104', name: '大渡口区', level: 'district' },
        { adcode: '500105', name: '江北区', level: 'district' },
        { adcode: '500106', name: '沙坪坝区', level: 'district' },
        { adcode: '500107', name: '九龙坡区', level: 'district' },
        { adcode: '500108', name: '南岸区', level: 'district' },
        { adcode: '500109', name: '北碚区', level: 'district' },
        { adcode: '500110', name: '渝北区', level: 'district' },
        { adcode: '500111', name: '巴南区', level: 'district' },
        { adcode: '500112', name: '长寿区', level: 'district' },
        { adcode: '500113', name: '江津区', level: 'district' },
        { adcode: '500114', name: '合川区', level: 'district' },
        { adcode: '500115', name: '永川区', level: 'district' },
        { adcode: '500116', name: '南川区', level: 'district' },
        { adcode: '500117', name: '綦江区', level: 'district' },
        { adcode: '500118', name: '大足区', level: 'district' },
        { adcode: '500119', name: '璧山区', level: 'district' },
        { adcode: '500120', name: '铜梁区', level: 'district' },
        { adcode: '500151', name: '潼南区', level: 'district' },
        { adcode: '500152', name: '荣昌区', level: 'district' },
        { adcode: '500153', name: '开州区', level: 'district' },
        { adcode: '500154', name: '梁平区', level: 'district' },
        { adcode: '500155', name: '武隆区', level: 'district' },
    ],
    '120100': [
        { adcode: '120101', name: '和平区', level: 'district' },
        { adcode: '120102', name: '河东区', level: 'district' },
        { adcode: '120103', name: '河西区', level: 'district' },
        { adcode: '120104', name: '南开区', level: 'district' },
        { adcode: '120105', name: '河北区', level: 'district' },
        { adcode: '120106', name: '红桥区', level: 'district' },
        { adcode: '120110', name: '东丽区', level: 'district' },
        { adcode: '120111', name: '西青区', level: 'district' },
        { adcode: '120112', name: '津南区', level: 'district' },
        { adcode: '120113', name: '北辰区', level: 'district' },
        { adcode: '120114', name: '武清区', level: 'district' },
        { adcode: '120115', name: '宝坻区', level: 'district' },
        { adcode: '120116', name: '滨海新区', level: 'district' },
        { adcode: '120117', name: '宁河区', level: 'district' },
        { adcode: '120118', name: '静海区', level: 'district' },
        { adcode: '120119', name: '蓟州区', level: 'district' },
    ],
};

/**
 * 获取静态省份数据
 */
export function getStaticProvinces(): RegionItem[] {
    return PROVINCES;
}

/**
 * 获取静态城市数据
 */
export function getStaticCities(parentAdcode: string): RegionItem[] {
    return CITIES[parentAdcode] || [];
}

/**
 * 获取静态区县数据
 */
export function getStaticDistricts(parentAdcode: string): RegionItem[] {
    return DISTRICTS[parentAdcode] || [];
}
